version: "2"
services:
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - /mnt/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLPWD
    restart: always  
volumes:
  {}
